satellites:
  - name: NOAA 19
    freq_mhz: 137.100
    tle1: "1 33591U 09005A   25311.12947422  .00000103  00000-0  78861-4 0  9996"
    tle2: "2 33591  98.9811  16.5585 0012848 300.4046  59.5856 14.13424405863114"
  - name: NOAA 18
    freq_mhz: 137.9125
    tle1: "1 28654U 05018A   25311.16954604  .00000171  00000-0  11378-3 0  9998"
    tle2: "2 28654  98.8324  28.8773 0015098  64.3220 295.9510 14.13662107 54940"
  - name: NOAA 15
    freq_mhz: 137.620
    tle1: "1 25338U 98030A   25310.29979011  .00000230  00000-0  11220-3 0  9994"
    tle2: "2 25338  98.5258 331.7692 0009117 282.0609  77.9551 14.27047903429507"
