satellites:
  - name: NOAA 19
    freq_mhz: 137.100
    tle1: "1 33591U 09005A   24310.91598214  .00000236  00000+0  25724-4 0  9995"
    tle2: "2 33591  99.1517 157.1577 0013580 101.6680 258.6154 14.12548312832257"
  - name: NOAA 18
    freq_mhz: 137.9125
    tle1: "1 28654U 05018A   24310.21598214  .00000114  00000+0  13360-4 0  9992"
    tle2: "2 28654  99.0768 201.0244 0014508 145.3483 214.8491 14.12183251901256"
